### ISSUE TITLE
Firebase.initializeApp is not mocked

### ISSUE THREAD

**Issue by AdrienLemaire** [atn832/fake_cloud_firestore#240]
Thanks for making and maintaining this repository.

I have a simple StatelessWidget with a StreamBuilder using `FirebaseFirestore.instance.collection('items').snapshots()`, and tests are broken now that I have introduced firebase to the project.

Test:
```dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:fake_cloud_firestore/fake_cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:project/src/features/home/home.dart';

Widget createHomeScreen() => MaterialApp(
      home: HomeScreen(),
    );

void main() {
  group('Home Screen Tests', () {
    testWidgets('Testing content', (tester) async {
      FakeFirebaseFirestore();
      await tester.pumpWidget(createHomeScreen());
      expect(find.text('My Button'), findsOneWidget);
    });
  });
}
```

Traceback:
```
$ flutter test
00:02 +1: /home/dori/Projects/Work/Company/Project/test/src/features/home/home_test.dart: Home Screen Tests Testing content
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following FirebaseException was thrown running a test:
[core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()

When the exception was thrown, this was the stack:
#0      MethodChannelFirebase.app (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:193:5)
#1      Firebase.app (package:firebase_core/src/firebase.dart:56:41)
#2      FirebaseFirestore.instance (package:cloud_firestore/src/firestore.dart:27:21)
#3      new HomeScreen (package:Project/src/features/home/view/home_screen.dart:8:32)
#4      createHomeScreen (file:///home/dori/Projects/Work/Company/Project/test/src/features/home/home_test.dart:8:13)
#5      main.<anonymous closure>.<anonymous closure> (file:///home/dori/Projects/Work/Company/Project/test/src/features/home/home_test.dart:19:31)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  Testing content
════════════════════════════════════════════════════════════════════════════════════════════════════
00:02 +1 -1: /home/dori/Projects/Work/Company/Project/test/src/features/home/home_test.dart: Home Screen Tests Testing content [E]
  Test failed. See exception logs above.
  The test description was: Testing content
```

In my case, `Firebase.initializeApp` is executed from `main.dart`, which isn't run from this test.
I understand that `Firebase.initializeApp` comes from the library `firebase_core`, while `fake_cloud_firestore` seems to mock `cloud_firestore`. But I'm surprised that nobody mentions this problem here. 
Isn't it correct that we cannot use firestore without doing first a `Firebase.initializeApp` ? How are we supposed to mock this part in our tests ? I was assuming that `FakeFirebaseFirestore` would handle that for us.

What is the proper way to mock Firebase ?

**Comment by atn832** [comment]
Basically, `FakeFirebaseFirestore()` acts like `FirebaseFirestore.instance`. It implements the same API. So in your code, instead of using directly `FirebaseFirestore.instance`, you should actually use an instance of `FirebaseFirestore`, be it the real one (`FirebaseFirestore.instance`) or the fake one (`FakeFirebaseFirestore()`).

The error message you are getting, which states that you did not call `Firebase.initializeApp`, shows that you are still running the real Firebase code (probably `FirebaseFirestore.instance`) somewhere in your test.

You can refer to https://firebase.flutter.dev/docs/testing/testing/, in which I give the full code to testing a simple app. You can see that only `main()` calls `Firebase.initializeApp`, and passes a real `FirebaseFirestore` instance to the Widget. The Widget is then initialized with an instance of `FirebaseFirestore`. On the opposite, during the tests, we pass a`FakeFirebaseFirestore` instead of the real implementation to the Widget.

Let me know if you still have issues!

**Comment by AdrienLemaire** [comment]
@atn832 thank you for taking the time to reply during the weekend.
I see. If the firestore instance is a widget parameter, we can easily replace the real instance with a fake one when calling the widget.

Are best practices discussed somewhere ? 
I'm new to flutter, and I suppose you don't define a firestore parameter on every screen widget, passing firestore around with each go_router route.

If I lift the firestore state up to the top App widget with provider, then use InheritedWidget to retrieve the firestore data in my components, I would need to wrap all related test components in a FakeApp widget.
Would that be a clean solution ?

Something like: 

```dart
Widget createHomeScreen() => ChangeNotifierProvider(
      create: (context) => FakeFirebaseFirestore(),
      child: MaterialApp(home: HomeScreen());
    );

void main() {
  group('Home Screen Tests', () {
    testWidgets('Testing content', (tester) async {
      await tester.pumpWidget(createHomeScreen());
    });
  });
}
```

**Comment by atn832** [comment]
Yes the sample code you propose is similar to what I use in my projects. I use `InheritedWidget` simply because it works well enough for my needs and doesn't add another dependency to the project. But the Provider API looks nice too!

Also I did not implement a `FirebaseWaiter` component because my app waits for several `Future`'s. So it was easier to inline the `FutureBuilder` like this:
```dart
WidgetsFlutterBinding.ensureInitialized();
runApp(
  FutureBuilder(
    future: Future.wait([
      SharedPreferences.getInstance(),
      Firebase.initializeApp(
          options: DefaultFirebaseOptions.currentPlatform)
    ]),
    builder: (context, snapshot) {
      if (!snapshot.hasData) {
        return [waiting state widget];
      }
      final sharedPreferences = snapshot.data.first as SharedPreferences;
      return MyApp(sharedPreferences);
    },
  ),
);
```

Finally, the first article's approach works, but it is quite complicated: they introduce an interface abstraction, implement the fake `CounterManager` and in the end manage to test only the Widget. It does not test the `FirestoreCounterManager` nor the fake `CounterManager`. If they wanted to be thorough, it would require even more work.

I haven't read the second article, but thanks for sharing! I'll read it later.

I haven't checked the official Flutter docs in a while, so I don't know if those practices are documented anywhere.

**Comment by AdrienLemaire** [comment]
Thanks! 
I now understand that the implementation differs depending on the code architecture and design patterns chosen.
It would be nice to have some examples for popular state management systems to get new flutter developers up to speed faster, but it's probably a bit out of scope for this library :)
